# Generated by Django 5.2.5 on 2025-08-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireWay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
