# Generated by Django 5.2.5 on 2025-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireWay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('questions', models.IntegerField(default=0)),
                ('topics', models.TextField()),
                ('category', models.CharField(choices=[('practice', 'Practice & Mockup Exam'), ('company', 'Company Test')], default='practice', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
