# Generated by Django 5.2.5 on 2025-08-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireWay_app', '0002_alter_job_options_alter_jobapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
