# Generated by Django 5.2.5 on 2025-08-30 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireWay_app', '0002_test_job_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=150)),
                ('template', models.CharField(choices=[('template1', 'Template 1'), ('template2', 'Template 2'), ('template3', 'Template 3')], default='template1', max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=250)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('passing_year', models.CharField(blank=True, max_length=10)),
                ('cgpa', models.CharField(blank=True, max_length=10)),
                ('objective', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated or newline-separated skills')),
                ('projects', models.TextField(blank=True, help_text='One project per line: Title - Description')),
                ('certifications', models.TextField(blank=True, help_text='One certification per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
